# DÃ©claration des stages dans l'ordre d'exÃ©cution
stages:
  - build
  - test
  - deploy

# Variables globales disponibles dans tous les jobs
variables:
  BUILD_ENV: dev

# --- STAGE BUILD ---
build:
  stage: build
  image: python:3.10-slim
  script:
    - echo "ðŸ“¦ Installation des dÃ©pendances..."
  
# --- STAGE TEST ---
test:
  stage: test
  image: python:3.10-slim
  script:
    - echo "ðŸ“¦ Test PART"

# --- STAGE DEPLOY ---
deploy:
  stage: deploy
  image: python:3.10-slim
  script:
    - echo "ðŸš€ DÃ©ploiement "
