services:
  database:
    image: mysql:8.0
    container_name: azendap_database_container
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "azendap_database"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend/
    container_name: azendap_backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

volumes:
  mysql_data: